ALTER TABLE request_trace
    ADD COLUMN IF NOT EXISTS client_id VARCHAR(128),
    ADD COLUMN IF NOT EXISTS model VARCHAR(255),
    ADD COLUMN IF NOT EXISTS provider VARCHAR(255),
    ADD COLUMN IF NOT EXISTS route_id VARCHAR(255),
    ADD COLUMN IF NOT EXISTS scene VARCHAR(255),
    ADD COLUMN IF NOT EXISTS status INTEGER,
    ADD COLUMN IF NOT EXISTS stream_mode VARCHAR(64),
    ADD COLUMN IF NOT EXISTS latency_ms BIGINT,
    ADD COLUMN IF NOT EXISTS error_message TEXT;
