-- H2-compatible version of webhook tables

CREATE TABLE IF NOT EXISTS webhook_endpoint (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    url VARCHAR(1000) NOT NULL,
    secret VARCHAR(500),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    event_types CLOB,
    retry_max INT NOT NULL DEFAULT 3,
    timeout_ms INT NOT NULL DEFAULT 5000,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS webhook_delivery_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    endpoint_id BIGINT NOT NULL,
    event_type VARCHAR(200),
    event_id VARCHAR(200),
    status VARCHAR(50) NOT NULL DEFAULT 'pending',
    http_status INT,
    attempts INT NOT NULL DEFAULT 0,
    last_error CLOB,
    payload CLOB,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delivered_at TIMESTAMP
);
